version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOST}

    ports:
      - 5432:5432
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    networks:
      - transcendence
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - transcendence
  
  django:
    build:
      context: ./django
    container_name: django
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8042:8042
    networks:
      - transcendence
    volumes: 
      - './django:/var/www/html'
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
    volumes:
      - './grafana:/var/lib/grafana'
      - './grafana/provisioning:/etc/grafana/provisioning'
    ports:
      - 3000:3000
    networks:
      - transcendence

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - './prometheus/:/etc/prometheus/'
    ports:
      - 9090:9090
    networks:
      - transcendence

  # elasticsearch:
  #   container_name: elasticsearch
  #   image: elasticsearch:8.11.3
  #   # volumes:
  #   #   - ./elasticsearch/config:/usr/share/elasticsearch/config
  #   environment:
  #     - ELASTICSEARCH_NODE_NAME=elasticsearch
  #     - ELASTICSEARCH_CLUSTER_NAME=elasticsearch
  #     - ELASTICSEARCH_ES_JAVA_OPTS=-Xmx256m -Xms256m
  #     - ELASTICSEARCH_NETWORK_HOST=localhost
  #     - ELASTICSEARCH_DISCOVERY_TYPE=single-node
  #     - ELASTICSEARCH_NODE_MASTER=true
  #     - ELASTICSEARCH_NODE_DATA=true
  #     - ELASTICSEARCH_HTTP_ENABLE=true
  #     - ELASTICSEARCH_HTTP_PORT=9200
  #     # Disable HTTPS
  #     - ELASTICSEARCH_HTTPS_ENABLE=false
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - transcendence

  # logstash:
  #   container_name: logstash
  #   image: logstash:8.11.3
  #   volumes:
  #     - ./logstash/config:/usr/share/logstash/config   #### CHECK THIS
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5044:5044
  #   networks:
  #     - transcendence

  # kibana:
  #   container_name: kibana
  #   image: kibana:8.11.3
  #   environment:
  #     ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOST}
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - transcendence

networks:
  transcendence:
    driver: bridge