# Generated by Django 4.2 on 2024-01-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.IntegerField(null=True, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=16)),
                ('totp_secret', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
