# Generated by Django 4.2 on 2024-02-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(max_length=32),
        ),
    ]
