apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: GET
      tlsSkipVerify: true

# dashboards:
#   - name: Dashboard
#     file: /etc/grafana/provisioning/dashboards/1_dashboard.json
#     folder: ""
#     overwrite: true